# Generated by Django 2.0.4 on 2018-05-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
