# Generated by Django 2.0.6 on 2018-06-22 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180509_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dateTodo',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
